fix: add missing dependencies in Dockerfile for R package installation
When installing R dependencies we get this error in the [pipeline](https://dev.azure.com/who-umc/Research/_build/results?buildId=161957&view=logs&j=1279e467-4f7d-534b-1a7d-fbfe5b54d697&t=91295751-36f0-5b26-8cf2-750deb768d9c)

```
Error: error testing if 'igraph' can be loaded [error code 1]
/usr/local/lib/R/bin/R --vanilla -s -f '/tmp/RtmpfK9bQ9/renv-install-176eff833.R'
================================================================================

Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/rlib/.renv/1/igraph/libs/igraph.so':
  libglpk.so.40: cannot open shared object file: No such file or directory
Calls: loadNamespace -> library.dynam -> dyn.load
```

and

```
-------------------------- [ERROR MESSAGE] ---------------------------
<stdin>:1:10: fatal error: fontconfig/fontconfig.h: No such file or directory
compilation terminated.
--------------------------------------------------------------------
ERROR: configuration failed for package ‘systemfonts’
* removing ‘/rlib/.renv/1/systemfonts’

25hError: failed to install "devtools", "pkgdown", "ragg", "systemfonts", "textshaping"
```